name: Simple CI 
on:
    push:
        branches: [main]
jobs:
    build:
         runs-on: ubuntu-latest
         steps:
            - name: Checkout 
              uses: actions/checkout@v4
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: Install Dependecnies
              run: npm install
            - name: Build Docker Image
              run: docker build -t test-application .
            - name: Run the Container
              run: docker run -d -p 3000:3000 test-application
            - name: Check the Container
              run: docker ps